export const SUPER_ADMIN_ROLE = 'SUPER_ADMIN_ROLE';
export const COMPANY_ADMIN_ROLE = 'COMPANY_ADMIN_ROLE';
export const SITE_ADMIN_ROLE = 'SITE_ADMIN_ROLE';
export const SECURITY_GUARD_ROLE = 'SECURITY_GUARD_ROLE';
export const ACCESS_TOKEN_KEY_NAME = 'access_token';